export const FETCH_REMINDERS = 'FETCH_REMINDERS';
export const ADD_REMINDER = 'ADD_REMINDER';
export const UPDATE_REMINDER = 'UPDATE_REMINDER';
export const REMOVE_REMINDER = 'REMOVE_REMINDER';
export const REMOVE_REMINDERS_BY_DATE = 'REMOVE_REMINDERS_BY_DATE';

export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
